### ISSUE TITLE
Tag latest release on GitHub

### ISSUE THREAD

**Issue by jonafato** [ikalnytskyi/gnome-shell-extension-icon-hider#31]
It appears that the latest release available on https://extensions.gnome.org/extension/351/icon-hider/ has no corresponding tag on GitHub. I'm packaging this extension for NixOS and would like to be able to fetch a tag from GitHub in the process. Can you upload a tagged release?

**Comment by theychx** [comment]
Should be fixed now.

**Comment by jonafato** [comment]
Thanks!
