### ISSUE TITLE
Not compatible with gjs >= 1.53.90

### ISSUE THREAD

**Issue by brunelli** [ikalnytskyi/gnome-shell-extension-icon-hider#35]
Trying to launch the extension preferences dialog gives the following:

```
SyntaxError: missing ( after for

Stack trace:
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:244:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398:5
  @<main>:1:43
  ```

**Comment by theychx** [comment]
That's odd, it's working for me (Debian Sid). Is Icon Hider the only extension where this is happening?

**Comment by brunelli** [comment]
GSConnect [was not working either](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/186), and this is the only other extension I have installed.

Maybe it can be related with Arch's packaging of gnome-shell?

**Comment by brunelli** [comment]
Ok, it's related to gjs.

Debian Sid has gjs 1.52.3, while Arch Linux has gjs 1.54.1.

[This](https://bugs.launchpad.net/ubuntu/+source/ubufox/+bug/1648649) may be related.

> Fortunately, it's easy to fix! Just replace code like this...
> `for each (let k in [...])`
> ...with code like this:
> `for (let k of [...])`

**Comment by theychx** [comment]
Cool, thanks. I'll try to make a hotfix.

**Comment by theychx** [comment]
Cheers, but those changes are listed as backwards-incompatible, which makes this a bit tricky.

**Comment by theychx** [comment]
> but those changes are listed as backwards-incompatible

Oh, it was the other way around. Haha :man_facepalming:
