### ISSUE TITLE
Push v21 on GNOME extensions

### ISSUE THREAD

**Issue by X0rg** [ikalnytskyi/gnome-shell-extension-icon-hider#37]
Hello,

I see v21 was released 2 days ago, but unfortunately, it is not available on GNOME extensions, so I'm stuck with a broken v20. :cry:

**Comment by theychx** [comment]
I submitted v21 for review at gnome.org the same day. So it should be there within the next few days.

**Comment by X0rg** [comment]
Ok, sorry for this useless issue.
Thank you.
