### ISSUE TITLE
Unable to scroll list 

### ISSUE THREAD

**Issue by varsop** [ikalnytskyi/gnome-shell-extension-icon-hider#38]
Some system tray icons reappear and for each time I start an application, which possesses a tray icon, they seem to have a different app-indicator ID. So every time I have to manually hide some apps via icon hider. But now the list of icons to hide is becoming too large and I can't even see the position where I could set the slider and I am not able to scroll this list. There is also no possibility to remove "old" app indicators from this list.  

It would help to be able to scroll this list of icons, which I want to hide. Many thanks in advance!

**Comment by theychx** [comment]
#29
